export default {
  'courses': [
    {
      'cls_dtl_id': 153,
      'start_day_name': '월요일',
      'start_day': 'WD1001',
      'time_index': 0,
      'subject': 'SJ1003',
      'program_name': '1학년 수학',
      'start_class_date': '11.04',
      'start_time': '17',
      'tutor_name': '전길',
      'during_time': '50',
      'grade': 'GD1001',
      'cls_user_mem_cnt': 4,
      'day_index': '1',
      'next_class_date': '10.29',
      'seq': 1,
      'group_seq': 1911,
    },
    {
      'cls_dtl_id': 189,
      'start_day_name': '목요일',
      'start_day': 'WD1004',
      'time_index': 0,
      'subject': 'SJ1003',
      'program_name': '1학년 수학',
      'start_class_date': '11.07',
      'start_time': '17',
      'tutor_name': '전길',
      'during_time': '50',
      'grade': 'GD1001',
      'cls_user_mem_cnt': 4,
      'day_index': '4',
      'seq': 1,
      'group_seq': 1911,
    },
    {
      'cls_dtl_id': 201,
      'start_day_name': '수요일',
      'start_day': 'WD1003',
      'time_index': 1,
      'subject': 'SJ1003',
      'program_name': '1학년 수학',
      'start_class_date': '11.06',
      'start_time': '18',
      'tutor_name': '전길',
      'during_time': '50',
      'grade': 'GD1001',
      'cls_user_mem_cnt': 4,
      'day_index': '3',
      'next_class_date': '11.06',
      'seq': 1,
      'group_seq': 1911,
    },
  ],
}
