POST https://qa-got.conects.com/elementary/class/apply/schedule/list
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=utf8

{
 "grade_id": "GD1001",
 "subject_id": "SJ1003"
}

###